// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: breeder.proto

package breeder

import (
	context "context"
	common "github.com/PedPet/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BreederMSG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *int32    `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Affix      string    `protobuf:"bytes,2,opt,name=affix,proto3" json:"affix,omitempty"`
	ShortAffix string    `protobuf:"bytes,3,opt,name=shortAffix,proto3" json:"shortAffix,omitempty"`
	Website    string    `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	Owners     []*Owners `protobuf:"bytes,5,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *BreederMSG) Reset() {
	*x = BreederMSG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breeder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreederMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreederMSG) ProtoMessage() {}

func (x *BreederMSG) ProtoReflect() protoreflect.Message {
	mi := &file_breeder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreederMSG.ProtoReflect.Descriptor instead.
func (*BreederMSG) Descriptor() ([]byte, []int) {
	return file_breeder_proto_rawDescGZIP(), []int{0}
}

func (x *BreederMSG) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *BreederMSG) GetAffix() string {
	if x != nil {
		return x.Affix
	}
	return ""
}

func (x *BreederMSG) GetShortAffix() string {
	if x != nil {
		return x.ShortAffix
	}
	return ""
}

func (x *BreederMSG) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *BreederMSG) GetOwners() []*Owners {
	if x != nil {
		return x.Owners
	}
	return nil
}

type Owners struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Forename string `protobuf:"bytes,1,opt,name=forename,proto3" json:"forename,omitempty"`
	Surname  string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Owners) Reset() {
	*x = Owners{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breeder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Owners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owners) ProtoMessage() {}

func (x *Owners) ProtoReflect() protoreflect.Message {
	mi := &file_breeder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owners.ProtoReflect.Descriptor instead.
func (*Owners) Descriptor() ([]byte, []int) {
	return file_breeder_proto_rawDescGZIP(), []int{1}
}

func (x *Owners) GetForename() string {
	if x != nil {
		return x.Forename
	}
	return ""
}

func (x *Owners) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Owners) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Owners) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetBreederRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBreederRequest) Reset() {
	*x = GetBreederRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breeder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBreederRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBreederRequest) ProtoMessage() {}

func (x *GetBreederRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breeder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBreederRequest.ProtoReflect.Descriptor instead.
func (*GetBreederRequest) Descriptor() ([]byte, []int) {
	return file_breeder_proto_rawDescGZIP(), []int{2}
}

func (x *GetBreederRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBreederRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBreederRequest) Reset() {
	*x = DeleteBreederRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breeder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBreederRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBreederRequest) ProtoMessage() {}

func (x *DeleteBreederRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breeder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBreederRequest.ProtoReflect.Descriptor instead.
func (*DeleteBreederRequest) Descriptor() ([]byte, []int) {
	return file_breeder_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBreederRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_breeder_proto protoreflect.FileDescriptor

var file_breeder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01,
	0x0a, 0x0a, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x4d, 0x53, 0x47, 0x12, 0x13, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x66, 0x66, 0x69, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x41, 0x66, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x41, 0x66, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x06, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xe7, 0x01, 0x0a, 0x07, 0x42, 0x72, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x72, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x12, 0x0b, 0x2e, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x4d, 0x53, 0x47,
	0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x12, 0x12, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x4d, 0x53, 0x47, 0x12, 0x29,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x12,
	0x0b, 0x2e, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x4d, 0x53, 0x47, 0x1a, 0x0b, 0x2e, 0x42,
	0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x4d, 0x53, 0x47, 0x12, 0x45, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x72, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50,
	0x65, 0x64, 0x50, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_breeder_proto_rawDescOnce sync.Once
	file_breeder_proto_rawDescData = file_breeder_proto_rawDesc
)

func file_breeder_proto_rawDescGZIP() []byte {
	file_breeder_proto_rawDescOnce.Do(func() {
		file_breeder_proto_rawDescData = protoimpl.X.CompressGZIP(file_breeder_proto_rawDescData)
	})
	return file_breeder_proto_rawDescData
}

var file_breeder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_breeder_proto_goTypes = []interface{}{
	(*BreederMSG)(nil),             // 0: BreederMSG
	(*Owners)(nil),                 // 1: Owners
	(*GetBreederRequest)(nil),      // 2: GetBreederRequest
	(*DeleteBreederRequest)(nil),   // 3: DeleteBreederRequest
	(*common.ConfirmResponse)(nil), // 4: common.proto.ConfirmResponse
}
var file_breeder_proto_depIdxs = []int32{
	1, // 0: BreederMSG.owners:type_name -> Owners
	0, // 1: Breeder.CreateBreeder:input_type -> BreederMSG
	2, // 2: Breeder.GetBreeder:input_type -> GetBreederRequest
	0, // 3: Breeder.UpdateBreeder:input_type -> BreederMSG
	3, // 4: Breeder.DeleteBreeder:input_type -> DeleteBreederRequest
	4, // 5: Breeder.CreateBreeder:output_type -> common.proto.ConfirmResponse
	0, // 6: Breeder.GetBreeder:output_type -> BreederMSG
	0, // 7: Breeder.UpdateBreeder:output_type -> BreederMSG
	4, // 8: Breeder.DeleteBreeder:output_type -> common.proto.ConfirmResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_breeder_proto_init() }
func file_breeder_proto_init() {
	if File_breeder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_breeder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreederMSG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_breeder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Owners); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_breeder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBreederRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_breeder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBreederRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_breeder_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_breeder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_breeder_proto_goTypes,
		DependencyIndexes: file_breeder_proto_depIdxs,
		MessageInfos:      file_breeder_proto_msgTypes,
	}.Build()
	File_breeder_proto = out.File
	file_breeder_proto_rawDesc = nil
	file_breeder_proto_goTypes = nil
	file_breeder_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BreederClient is the client API for Breeder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BreederClient interface {
	CreateBreeder(ctx context.Context, in *BreederMSG, opts ...grpc.CallOption) (*common.ConfirmResponse, error)
	GetBreeder(ctx context.Context, in *GetBreederRequest, opts ...grpc.CallOption) (*BreederMSG, error)
	UpdateBreeder(ctx context.Context, in *BreederMSG, opts ...grpc.CallOption) (*BreederMSG, error)
	DeleteBreeder(ctx context.Context, in *DeleteBreederRequest, opts ...grpc.CallOption) (*common.ConfirmResponse, error)
}

type breederClient struct {
	cc grpc.ClientConnInterface
}

func NewBreederClient(cc grpc.ClientConnInterface) BreederClient {
	return &breederClient{cc}
}

func (c *breederClient) CreateBreeder(ctx context.Context, in *BreederMSG, opts ...grpc.CallOption) (*common.ConfirmResponse, error) {
	out := new(common.ConfirmResponse)
	err := c.cc.Invoke(ctx, "/Breeder/CreateBreeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breederClient) GetBreeder(ctx context.Context, in *GetBreederRequest, opts ...grpc.CallOption) (*BreederMSG, error) {
	out := new(BreederMSG)
	err := c.cc.Invoke(ctx, "/Breeder/GetBreeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breederClient) UpdateBreeder(ctx context.Context, in *BreederMSG, opts ...grpc.CallOption) (*BreederMSG, error) {
	out := new(BreederMSG)
	err := c.cc.Invoke(ctx, "/Breeder/UpdateBreeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breederClient) DeleteBreeder(ctx context.Context, in *DeleteBreederRequest, opts ...grpc.CallOption) (*common.ConfirmResponse, error) {
	out := new(common.ConfirmResponse)
	err := c.cc.Invoke(ctx, "/Breeder/DeleteBreeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreederServer is the server API for Breeder service.
type BreederServer interface {
	CreateBreeder(context.Context, *BreederMSG) (*common.ConfirmResponse, error)
	GetBreeder(context.Context, *GetBreederRequest) (*BreederMSG, error)
	UpdateBreeder(context.Context, *BreederMSG) (*BreederMSG, error)
	DeleteBreeder(context.Context, *DeleteBreederRequest) (*common.ConfirmResponse, error)
}

// UnimplementedBreederServer can be embedded to have forward compatible implementations.
type UnimplementedBreederServer struct {
}

func (*UnimplementedBreederServer) CreateBreeder(context.Context, *BreederMSG) (*common.ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBreeder not implemented")
}
func (*UnimplementedBreederServer) GetBreeder(context.Context, *GetBreederRequest) (*BreederMSG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBreeder not implemented")
}
func (*UnimplementedBreederServer) UpdateBreeder(context.Context, *BreederMSG) (*BreederMSG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBreeder not implemented")
}
func (*UnimplementedBreederServer) DeleteBreeder(context.Context, *DeleteBreederRequest) (*common.ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBreeder not implemented")
}

func RegisterBreederServer(s *grpc.Server, srv BreederServer) {
	s.RegisterService(&_Breeder_serviceDesc, srv)
}

func _Breeder_CreateBreeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreederMSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreederServer).CreateBreeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Breeder/CreateBreeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreederServer).CreateBreeder(ctx, req.(*BreederMSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breeder_GetBreeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBreederRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreederServer).GetBreeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Breeder/GetBreeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreederServer).GetBreeder(ctx, req.(*GetBreederRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breeder_UpdateBreeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreederMSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreederServer).UpdateBreeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Breeder/UpdateBreeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreederServer).UpdateBreeder(ctx, req.(*BreederMSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breeder_DeleteBreeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBreederRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreederServer).DeleteBreeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Breeder/DeleteBreeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreederServer).DeleteBreeder(ctx, req.(*DeleteBreederRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Breeder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Breeder",
	HandlerType: (*BreederServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBreeder",
			Handler:    _Breeder_CreateBreeder_Handler,
		},
		{
			MethodName: "GetBreeder",
			Handler:    _Breeder_GetBreeder_Handler,
		},
		{
			MethodName: "UpdateBreeder",
			Handler:    _Breeder_UpdateBreeder_Handler,
		},
		{
			MethodName: "DeleteBreeder",
			Handler:    _Breeder_DeleteBreeder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breeder.proto",
}
